package frontend

const searchTemplate = `{{define "search"}}<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>근거 검색 · SyncBase</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/css/app.css"></head>
<body class="app-body"><div class="app-shell"><aside class="sidebar"><a class="sidebar-brand" href="/documents"><span class="brand-mark"><span></span><span></span><span></span></span><span><strong>SyncBase</strong><small>지식 운영 · Go</small></span></a><nav class="sidebar-nav"><a href="/documents">문서</a><a class="active" href="/search">근거 검색</a></nav><div class="sidebar-spacer"></div>{{if .Environment}}<div class="system-info"><span class="status-dot"></span>{{.Environment}}</div>{{end}}</aside><section class="workspace"><header class="topbar"><div><span>운영 지식베이스</span><strong>MCP 근거 검색</strong></div></header>
<main class="content"><div class="page-heading"><div><p class="overline">GROUNDED SEARCH · MCP</p><h1>근거 검색</h1><p>활성화된 최신 문서 버전만 검색하고 정확한 원문 페이지를 엽니다.</p></div></div>
<section class="search-content"><form action="/search" method="get" class="search-form"><span>⌕</span><input name="q" value="{{.Query}}" maxlength="2000" aria-label="검색 질문" placeholder="예: 비밀번호 변경 주기는 어떻게 되나요?" required><button type="submit">실제 MCP 검색</button></form><p class="search-hint">공식 MCP tools/call로 최신 활성 버전만 조회합니다.</p>{{if .Error}}<p class="alert">{{.Error}}</p>{{end}}
{{if .Query}}<section class="search-results"><div class="result-summary"><div><strong>검색 결과</strong><span>“{{.Query}}”</span></div><span>{{len .Hits}}건</span></div>{{if .Hits}}{{range .Hits}}<article class="search-result"><div class="result-rank">{{.Rank}}</div><div class="result-body"><div class="result-meta"><span>{{.DocumentName}}</span><span>v{{.DocumentVersion}}</span><span>{{.PageNumber}}페이지</span><span>점수 {{printf "%.3f" .Score}}</span></div><p>{{.Snippet}}</p><a class="source-link" href="{{.SourceURL}}">정확한 원문 페이지 열기 →</a><details class="audit-panel"><summary>MCP 근거 정보</summary><div><code>{{.DocumentID}} · v{{.DocumentVersion}} · p{{.PageNumber}}</code></div></details></div></article>{{end}}{{else if not .Error}}<div class="empty-results"><h2>기준 점수 이상의 근거가 없습니다</h2><p>표현을 바꾸거나 검색 가능한 문서를 확인하세요.</p></div>{{end}}</section>{{end}}</section>
</main></section></div></body></html>{{end}}`
