// Package frontend owns the embedded SyncBase administrator console assets.
package frontend

import (
	"html/template"
)

// Parse adds all frontend templates to base. Callers provide the function map
// because template functions operate on WAS-owned domain types.
func Parse(base *template.Template) (*template.Template, error) {
	root := base
	for _, source := range []string{loginTemplate, documentsTemplate, uploadTemplate, detailsTemplate, sourceTemplate, searchTemplate} {
		var err error
		root, err = root.Parse(source)
		if err != nil {
			return nil, err
		}
	}
	return root, nil
}

const loginTemplate = `{{define "login"}}<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>로그인 · SyncBase</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/css/app.css"></head>
<body class="auth-page"><main class="auth-layout">
<section class="auth-intro"><div class="auth-brand"><span class="brand-mark light"><span></span><span></span><span></span></span><strong>SyncBase</strong></div>
<div class="auth-message"><p class="overline">OPERATIONS KNOWLEDGE</p><h1>운영 문서를<br>검색 가능한 지식으로</h1><p>최신 버전만 정확하게 반영하고, 모든 검색 결과를 원문 페이지까지 연결합니다.</p></div>
<div class="auth-capabilities"><span>버전 관리</span><span>자동 인덱싱</span><span>근거 검색</span></div></section>
<section class="auth-panel"><div class="auth-form-wrap"><p class="overline">ADMIN CONSOLE · GO</p><h2>관리자 로그인</h2><p class="muted">운영 지식베이스를 관리하려면 로그인하세요.</p>
{{if .Error}}<p class="alert">아이디 또는 비밀번호를 확인하세요.</p>{{end}}
<form action="/login" method="post" class="stack auth-form"><input type="hidden" name="next" value="{{.Next}}"><label>아이디<input name="username" value="{{.Username}}" autocomplete="username" required autofocus></label><label>비밀번호<input name="password" type="password" autocomplete="current-password" required></label><button type="submit">로그인</button></form>
<p class="auth-help">관리자 계정에 문제가 있으면 시스템 담당자에게 문의하세요.</p></div></section>
</main></body></html>{{end}}`

const documentsTemplate = `{{define "documents"}}<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>문서 · SyncBase</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/css/app.css"></head>
<body class="app-body"><div class="app-shell"><aside class="sidebar"><a class="sidebar-brand" href="/documents"><span class="brand-mark"><span></span><span></span><span></span></span><span><strong>SyncBase</strong><small>지식 운영 · Go</small></span></a><nav class="sidebar-nav"><a class="active" href="/documents"><svg viewBox="0 0 24 24"><path d="M7 3.5h7l4 4V20a.5.5 0 0 1-.5.5h-11A.5.5 0 0 1 6 20V4a.5.5 0 0 1 .5-.5Z"/><path d="M14 3.5V8h4M9 12h6M9 15.5h6"/></svg>문서</a><a href="/search">근거 검색</a></nav><div class="sidebar-spacer"></div>{{if .Environment}}<div class="system-info"><span class="status-dot"></span>{{.Environment}}</div>{{end}}<div class="sidebar-user"><span class="user-avatar">관</span><span><strong>관리자</strong><small>문서 운영자</small></span></div></aside>
<section class="workspace"><header class="topbar"><div><span>운영 지식베이스</span><strong>문서</strong></div><form action="/logout" method="post"><input type="hidden" name="csrf" value="{{.CSRF}}"><button class="text-button">로그아웃</button></form></header>
<main class="content"><div class="page-heading"><div><p class="overline">KNOWLEDGE LIBRARY</p><h1>문서</h1><p>검색에 사용할 운영 문서와 최신 반영 상태를 관리합니다.</p></div><a class="button" href="/documents/new">＋ PDF 등록</a></div>
<section class="metric-strip"><div><span>전체 문서</span><strong>{{.Total}}</strong></div><div><span>검색 가능</span><strong>{{.Searchable}}</strong></div><div><span>처리 중</span><strong>{{.Processing}}</strong></div><div><span>확인 필요</span><strong>{{.Attention}}</strong></div></section>
<section class="library-panel"><div class="panel-heading"><div><h2>문서 라이브러리</h2><p>{{.Total}}개의 문서</p></div></div>
{{if .Documents}}<div class="table-wrap"><table class="document-table"><thead><tr><th>문서</th><th>검색 버전</th><th>상태</th><th>최근 변경</th><th></th></tr></thead><tbody>{{range .Documents}}<tr><td><a class="document-cell" href="/documents/{{.ID}}"><span class="pdf-icon">PDF</span><span><strong>{{.Name}}</strong><small>최신 등록 v{{.LatestVersion}}</small></span></a></td><td><strong>{{activeVersion .ActiveVersion}}</strong></td><td><span class="status-badge {{.LatestStatus}}">{{statusLabel .LatestStatus}}</span></td><td><time>{{formatTime .UpdatedAt}}</time></td><td><a class="row-action" href="/documents/{{.ID}}">→</a></td></tr>{{end}}</tbody></table></div>
{{else}}<div class="empty-state"><span class="empty-icon">⌁</span><h3>첫 운영 문서를 등록하세요</h3><p>텍스트 PDF를 등록하면 자동 분석해 근거 검색에 반영합니다.</p><a class="button secondary" href="/documents/new">PDF 등록 시작</a></div>{{end}}</section></main></section></div></body></html>{{end}}`

const uploadTemplate = `{{define "upload"}}<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="_csrf" content="{{.CSRF}}"><meta name="_csrf_header" content="X-CSRF-Token"><title>PDF 등록 · SyncBase</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/css/app.css"></head>
<body class="app-body"><div class="app-shell"><aside class="sidebar"><a class="sidebar-brand" href="/documents"><span class="brand-mark"><span></span><span></span><span></span></span><span><strong>SyncBase</strong><small>지식 운영 · Go</small></span></a><nav class="sidebar-nav"><a class="active" href="/documents">문서</a><a href="/search">근거 검색</a></nav><div class="sidebar-spacer"></div></aside><section class="workspace"><header class="topbar"><div><span>운영 지식베이스</span><strong>PDF 등록</strong></div></header>
<main class="content upload-content"><a class="back-link" href="{{if .Document}}/documents/{{.Document.ID}}{{else}}/documents{{end}}">← 문서로 돌아가기</a><div class="page-heading compact"><div><p class="overline">{{if .Document}}NEW VERSION{{else}}NEW DOCUMENT{{end}}</p><h1>{{if .Document}}{{.Document.Name}}{{else}}문서 등록{{end}}</h1><p>{{if .Document}}새 PDF가 준비될 때까지 현재 검색 버전은 그대로 유지됩니다.{{else}}PDF를 등록하면 검색 가능한 지식으로 자동 처리합니다.{{end}}</p></div></div>
<ol class="upload-steps"><li class="active"><span>1</span>파일 선택</li><li><span>2</span>사전 확인</li><li><span>3</span>처리 시작</li></ol><div class="upload-grid"><section class="form-panel"><form id="upload-form" action="{{.Action}}" method="post" enctype="multipart/form-data" class="stack"><input type="hidden" name="csrf" value="{{.CSRF}}"><input type="hidden" name="requestKey" id="request-key"><label class="upload-dropzone"><input id="pdf-file" type="file" name="file" accept="application/pdf,.pdf" required><span class="upload-symbol">↑</span><strong>PDF 파일 선택</strong><small>클릭하여 파일을 선택하세요</small></label>{{if not .Document}}<label class="field"><span>문서명</span><input id="document-name" name="documentName" minlength="1" maxlength="200" placeholder="예: 기업 운영 정책" required></label>{{end}}<section id="preflight" class="file-review" hidden><div class="file-review-title"><span class="pdf-icon">PDF</span><div><strong id="preflight-name"></strong><small>파일 확인 완료</small></div><span class="check-mark">✓</span></div><dl><div><dt>크기</dt><dd id="preflight-size"></dd></div><div><dt>페이지</dt><dd id="preflight-pages"></dd></div><div><dt>텍스트</dt><dd>추출 가능</dd></div></dl></section><p id="preflight-error" class="alert" hidden></p><button id="submit-upload" type="submit" disabled>{{if .Document}}새 버전 등록하고 처리 시작{{else}}등록하고 처리 시작{{end}}</button></form><section id="upload-recovery" class="recovery-panel" hidden><h2>등록 상태를 확인하고 있습니다</h2><p id="recovery-message"></p><details><summary>복구 정보</summary><p class="small">복구 코드 <code id="recovery-code"></code></p><a id="recovery-url" href="#">복구 상태 확인</a></details></section></section>
<aside class="guidance-panel"><h2>등록 전 확인</h2><ul><li><span>✓</span>텍스트가 포함된 PDF</li><li><span>✓</span>최대 100MB, 500페이지</li><li><span>✓</span>암호화되지 않은 파일</li></ul><div class="processing-note"><strong>등록 후 자동 처리</strong><p>텍스트 추출, 문단 분리, 검색 특징 생성을 거쳐 최신 버전만 검색에 반영됩니다.</p></div></aside></div></main></section></div><script type="module" src="/js/upload.js"></script></body></html>{{end}}`

const detailsTemplate = `{{define "details"}}<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">{{if .Processing}}<meta http-equiv="refresh" content="2">{{end}}<title>{{.Document.Name}} · SyncBase</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/css/app.css"></head>
<body class="app-body"><div class="app-shell"><aside class="sidebar"><a class="sidebar-brand" href="/documents"><span class="brand-mark"><span></span><span></span><span></span></span><span><strong>SyncBase</strong><small>지식 운영 · Go</small></span></a><nav class="sidebar-nav"><a class="active" href="/documents">문서</a><a href="/search">근거 검색</a></nav><div class="sidebar-spacer"></div></aside><section class="workspace"><header class="topbar"><div><span>운영 지식베이스</span><strong>문서 상세</strong></div></header>
<main class="content document-detail"><a class="back-link" href="/documents">← 문서 목록</a>{{if .Registered}}<p class="notice toast">등록했습니다. Worker가 실제 PDF 처리를 시작합니다.</p>{{end}}<div class="page-heading"><div><p class="overline">DOCUMENT</p><h1>{{.Document.Name}}</h1><p>{{if .Document.ActiveVersion}}최신 운영 문서와 검색 반영 상태를 확인합니다.{{else if .Processing}}검색 반영을 준비하고 있습니다.{{else}}검색 반영이 필요합니다. 오류를 확인하거나 새 버전을 등록하세요.{{end}}</p></div><div class="heading-actions"><a class="button" href="/documents/{{.Document.ID}}/versions/new">새 버전 등록</a></div></div>
<section id="document-status-region">{{if .Document.ActiveVersion}}<div class="active-summary"><span class="summary-icon">✓</span><div><p>현재 검색 버전은 {{activeVersion .Document.ActiveVersion}}입니다</p><small>{{if .Processing}}새 버전을 처리하는 동안 기존 검색 결과는 안전하게 유지됩니다.{{else}}검색 결과는 이 버전의 원문 페이지로 연결됩니다.{{end}}</small></div><span class="status-badge ACTIVE">검색 가능</span></div>{{else if .Processing}}<div class="active-summary waiting"><span class="summary-icon">↻</span><div><p>첫 버전을 처리하고 있습니다</p><small>완료되면 최신 버전만 검색에 반영됩니다.</small></div><span class="status-badge PROCESSING">처리 중</span></div>{{else}}<div class="active-summary failed-summary"><span class="summary-icon">!</span><div><p>검색 반영이 필요합니다</p><small>아래 오류와 복구 가능 여부를 확인하세요.</small></div><span class="status-badge FAILED">확인 필요</span></div>{{end}}
<div class="detail-grid"><section class="version-section"><div class="section-heading"><div><h2>버전 및 처리 현황</h2><p>등록 순서와 실제 처리 단계를 확인할 수 있습니다.</p></div></div>{{range $version := .Document.Versions}}<article class="version-card"><div class="version-header"><div><strong>v{{$version.VersionNumber}}</strong><span class="status-badge {{$version.Status}}">{{statusLabel $version.Status}}</span>{{if $version.Active}}<span class="active-label">현재 검색 버전</span>{{end}}</div><time>{{formatTime $version.UpdatedAt}}</time></div><div class="pipeline"><ol class="stage-track">{{range $stage := stages}}{{$state := stageState $version $stage}}<li class="{{$state}}"><span class="stage-mark">{{if eq $state "complete"}}✓{{else if eq $state "failed"}}!{{end}}</span><span><strong>{{stageLabel $stage}}</strong><small>{{stageStateLabel $state}}</small></span></li>{{end}}</ol></div>{{if or (isProcessing $version.Status) (eq $version.Status "FAILED")}}{{if gt $version.AutomaticAttempts 0}}<p class="small">자동 처리 시도 <strong>{{$version.AutomaticAttempts}} / 3</strong>{{if $version.NextAutomaticRetryAt}} · 다음 시도 {{formatTimePtr $version.NextAutomaticRetryAt}}{{end}}{{if gt $version.QueuePosition 0}} · 대기 순서 {{$version.QueuePosition}}{{end}}</p>{{end}}{{end}}{{if $version.ErrorCode}}<p class="alert">{{errorLabel $version.ErrorCode}} 오류 코드: <code>{{$version.ErrorCode}}</code></p>{{end}}<div class="version-footer"><span>{{if $version.PageCount}}{{$version.PageCount}}페이지{{else}}페이지 확인 중{{end}}</span><div class="actions">{{if $version.PageCount}}<a href="/sources/{{$.Document.ID}}/versions/{{$version.VersionNumber}}?page=1">원문 보기</a>{{end}}{{if $version.ManualRetryAllowed}}<form action="/processing-runs/{{$version.RunID}}/retry" method="post"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="documentId" value="{{$.Document.ID}}"><input type="hidden" name="requestKey" value="retry-{{$version.RunID}}"><button class="text-button">처리 재시도</button></form>{{end}}</div></div><details class="technical-details"><summary>기술 세부 정보</summary><dl><div><dt>버전 ID</dt><dd><code>{{$version.ID}}</code></dd></div><div><dt>처리 작업</dt><dd><code>{{$version.RunID}}</code></dd></div><div><dt>상관 ID</dt><dd><code>{{$version.CorrelationID}}</code></dd></div><div><dt>현재 단계</dt><dd><code>{{$version.Stage}}</code></dd></div></dl></details></article>{{end}}</section>
<aside class="metadata-panel"><h2>문서 정보</h2><dl><div><dt>문서명</dt><dd>{{.Document.Name}}</dd></div><div><dt>현재 검색 버전</dt><dd>{{activeVersion .Document.ActiveVersion}}</dd></div><div><dt>등록된 버전</dt><dd>{{len .Document.Versions}}개</dd></div><div><dt>문서 ID</dt><dd><code>{{.Document.ID}}</code></dd></div></dl></aside></div></section></main></section></div></body></html>{{end}}`

const sourceTemplate = `{{define "source"}}<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{.Source.Name}} v{{.Source.Version}}</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/css/app.css"><link rel="modulepreload" href="/vendor/pdfjs/pdf.mjs"></head>
<body class="app-body"><div class="app-shell"><aside class="sidebar"><a class="sidebar-brand" href="/documents"><span class="brand-mark"><span></span><span></span><span></span></span><span><strong>SyncBase</strong><small>지식 운영 · Go</small></span></a><nav class="sidebar-nav"><a class="active" href="/documents">문서</a><a href="/search">근거 검색</a></nav><div class="sidebar-spacer"></div></aside><section class="workspace"><header class="topbar"><div><span>운영 지식베이스</span><strong>원문 보기</strong></div></header><main class="viewer-content"><div class="viewer-heading"><a class="back-link" href="/documents/{{.Source.DocumentID}}">← 문서 상세</a><div><div><p class="overline">SOURCE DOCUMENT</p><h1>{{.Source.Name}}</h1></div><span class="version-chip">v{{.Source.Version}} · {{.Page}}페이지</span></div></div><div class="viewer-layout"><section class="viewer-canvas-wrap"><div class="viewer-toolbar"><span><strong>{{.Page}}</strong> / {{.Source.PageCount}} 페이지</span><a id="raw-pdf-link" href="/sources/{{.Source.DocumentID}}/versions/{{.Source.Version}}/raw.pdf#page={{.Page}}">원본 PDF 열기 · {{.Page}}페이지</a></div><p id="viewer-status" role="status">정확한 원문 페이지를 렌더링하고 있습니다.</p><div id="pdf-page" class="pdf-page" data-page="{{.Page}}" data-pdf-url="/sources/{{.Source.DocumentID}}/versions/{{.Source.Version}}/raw.pdf"><canvas id="pdf-canvas" aria-label="{{.Source.Name}} {{.Page}}페이지"></canvas><div id="text-layer" class="text-layer textLayer" aria-label="선택 가능한 PDF 텍스트"></div></div><p id="viewer-fallback" class="viewer-fallback" hidden>브라우저 렌더링을 완료하지 못했습니다. <a href="/sources/{{.Source.DocumentID}}/versions/{{.Source.Version}}/raw.pdf#page={{.Page}}">정확한 원본 페이지를 여세요.</a></p></section><aside class="source-panel"><span class="source-check">✓</span><h2>검색 근거 위치</h2><p>검색 결과가 가리킨 정확한 문서 버전과 페이지입니다.</p><dl><div><dt>문서</dt><dd>{{.Source.Name}}</dd></div><div><dt>버전</dt><dd>v{{.Source.Version}}</dd></div><div><dt>페이지</dt><dd>{{.Page}}페이지</dd></div></dl><details class="technical-details source-technical"><summary>기술 출처 정보</summary><dl><div><dt>문서 ID</dt><dd><code>{{.Source.DocumentID}}</code></dd></div><div><dt>source_url</dt><dd><code>{{.SourceURL}}</code></dd></div></dl></details></aside></div></main></section></div><script type="module" src="/js/source-viewer.mjs"></script></body></html>{{end}}`
